### ISSUE TITLE
Move builds to C++14 on windows

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/abseil-cpp-feedstock#37]
As of https://github.com/abseil/abseil-cpp/commit/97ab3dcfd6490434202e4ab00b2eaba9449e42a1 (not yet in a released version), abseil-cpp requires C++14.

Heads-up especially for the arrow-team, who mentioned still being bound to C++11 on windows some time ago. @conda-forge/arrow-cpp

**Comment by hmaarrfk** [comment]
I think we can close this correct? The trend is now to move to C++17.

This is in large part due to your effort in moving to VS2019 😄

**Comment by h-vetinari** [comment]
> I think we can close this correct? The trend is now to move to C++17.
> 
> This is in large part due to your effort in moving to VS2019 smile

Actually, VS2017 has almost complete support (except one library feature) for C++17, but your point is well taken. ;)
